language: scala
sudo: false

cache:
  directories:
  - "$HOME/.m2"

install:
  - which java
  - mvn install -DskipTests=true -DskipITs=true -Dmaven.javadoc.skip=true -B -V --toolchains .m2/travis-ci-toolchains.xml

jobs:
  include:
  - stage: test
    scala: 2.11
    script: mvn test -pl scala/scala_2.11 -B --toolchains .m2/travis-ci-toolchains.xml
    jdk: openjdk8
  - stage: test
    scala: 2.12
    script: mvn test -pl scala/scala_2.12,examples -B --toolchains .m2/travis-ci-toolchains.xml
    jdk: openjdk8
  - stage: test
    scala: 2.13
    script: mvn test -pl scala/scala_2.13,examples -B --toolchains .m2/travis-ci-toolchains.xml
    jdk: openjdk8
branches:
  only:
  - master
